"""Additional tests to improve code coverage."""
import unittest
import yamldoc
from yamldoc.entries import MetaEntry, Entry, sanitize_meta
from yamldoc.parser import strip_footer, count_indent, key_value


class TestEntries(unittest.TestCase):
    """Test entry classes for coverage."""

    def test_sanitize_meta_with_override(self):
        """Test sanitize_meta with override_exclude flag."""
        meta, exclude = sanitize_meta("#'! Excluded", "#'", "#'!", override_exclude=True)
        self.assertEqual(meta, "Excluded")
        self.assertFalse(exclude)  # Should be False due to override

    def test_meta_entry_repr_with_schema(self):
        """Test MetaEntry __repr__ with schema."""
        entry = MetaEntry("test", "meta", "#'")
        entry.has_schema = True
        entry.entries = []
        repr_str = repr(entry)
        self.assertIn("with schema", repr_str)
        self.assertIn("n = 0", repr_str)

    def test_meta_entry_repr_without_schema(self):
        """Test MetaEntry __repr__ without schema."""
        entry = MetaEntry("test", "meta", "#'")
        entry.has_schema = False
        entry.entries = []
        repr_str = repr(entry)
        self.assertIn("without schema", repr_str)
        self.assertIn("n = 0", repr_str)

    def test_meta_entry_excluded(self):
        """Test MetaEntry to_markdown when excluded."""
        entry = MetaEntry("test", "#'! Excluded", "#'", "#'!")
        markdown = entry.to_markdown()
        self.assertEqual(markdown, "")

    def test_meta_entry_no_entries(self):
        """Test MetaEntry to_markdown with no member variables."""
        entry = MetaEntry("test", "#' Some meta", "#'")
        entry.entries = []
        markdown = entry.to_markdown()
        self.assertIn("No member variables", markdown)
        self.assertIn("## `test`", markdown)

    def test_entry_excluded(self):
        """Test Entry to_markdown when excluded."""
        entry = Entry("key", "value", "#'! Excluded", "#'", "#'!")
        markdown = entry.to_markdown()
        self.assertEqual(markdown, "")

    def test_entry_repr_with_type(self):
        """Test Entry __repr__ with type information."""
        entry = Entry("key", "value", "meta", "#'")
        entry.type = "string"
        repr_str = repr(entry)
        self.assertIn("Type: string", repr_str)

    def test_entry_to_markdown_with_none_type(self):
        """Test Entry to_markdown with None type and schema=True."""
        entry = Entry("key", "value", "meta", "#'")
        entry.type = None
        markdown = entry.to_markdown(schema=True)
        self.assertIn("Unknown", markdown)


class TestParserUtilities(unittest.TestCase):
    """Test parser utility functions."""

    def test_count_indent(self):
        """Test count_indent function."""
        self.assertEqual(count_indent("no indent"), 0)
        self.assertEqual(count_indent("  two spaces"), 2)
        self.assertEqual(count_indent("    four spaces"), 4)

    def test_key_value_with_colon_in_value(self):
        """Test key_value when value contains colons."""
        result = key_value("url: https://example.com:8080")
        self.assertEqual(result, ("url", "https://example.com:8080"))

    def test_key_value_no_value(self):
        """Test key_value when there's no value."""
        result = key_value("key:")
        self.assertEqual(result, "key")

    def test_strip_footer(self):
        """Test strip_footer function."""
        md_with_footer = "# Title\n\nContent\n\n---\nGenerated by [yamldoc](https://github.com/chris1221/yaml.doc) v0.1.6\n"
        stripped = strip_footer(md_with_footer)
        self.assertNotIn("Generated by", stripped)
        self.assertIn("# Title", stripped)
        self.assertIn("Content", stripped)

    def test_strip_footer_no_footer(self):
        """Test strip_footer when there's no footer."""
        md_no_footer = "# Title\n\nContent\n"
        stripped = strip_footer(md_no_footer)
        self.assertEqual(md_no_footer, stripped)


class TestMainFunction(unittest.TestCase):
    """Test main function with different parameters."""

    def test_main_without_footer(self):
        """Test main function with footer=False."""
        import sys
        import io

        old_stdout = sys.stdout
        new_stdout = io.StringIO()
        sys.stdout = new_stdout

        yamldoc.main(
            yaml_path="test/yaml/basic.yaml",
            footer=False
        )

        output = new_stdout.getvalue()
        sys.stdout = old_stdout

        self.assertNotIn("Generated by", output)
        self.assertIn("Configuration Parameters Reference", output)

    def test_main_with_custom_title_description(self):
        """Test main function with custom title and description."""
        import sys
        import io

        old_stdout = sys.stdout
        new_stdout = io.StringIO()
        sys.stdout = new_stdout

        yamldoc.main(
            yaml_path="test/yaml/basic.yaml",
            title="Custom Title",
            description="Custom description text.",
            footer=False
        )

        output = new_stdout.getvalue()
        sys.stdout = old_stdout

        self.assertIn("Custom Title", output)
        self.assertIn("Custom description text", output)


if __name__ == "__main__":
    unittest.main()
